Tydligare utseende och mer information
u9n/hanporten pull request #11
Opened 2021-06-23 08:48 UTC by GETEXSM

Jag la till Kamstrup mätaren, som ändå är en av dem största spelarna på marknaden just nu.
Samt 2 bolag som jag vet använder dem i sin helet.

2021-06-30 09:26 UTC, Krolken commented
Tack för tillägget.
Men jag försöker hålla allting i Markdown så jag kan inte merge HTML formatering.

Jag tror inte att en tabell är rätt för elnätbolags-sidan. Fördelen med att hålla det i rubriker är att man får en innehållsförteckning till sidan och bättre SEO.

Men man skulle kunna ha en tabell för mätare under varje rubrik.

Mätare | Port 
--- | ---
Landis | Svensk (RJ12)

2021-06-30 10:17 UTC, GETEXSM commented
SEO ? Det är bara något man bryr sig om man ska pusha reklam eller vinstintresse, detta är en tekniksida likt Wikipedia som ska vara lätt att läsa för människor.
Om du skulle få alla elbolag i den listan så skulle den bli enormt lång sida, samt 80% dött utrymme till höger om texten.
Istället med Tabell så formateras allt så den tar upp mer av sidans bredd och man forcerar in informationen likt andra har skrivet den, annars kommer det garanterat bli så rörigt att snabbt leta upp exakt vad man letar efter då folk kommer skriva på olika sätt, som du redan gjort.
Sen vad menar du med Markdown ? ska du bygga hel hemsida utan HTML ? du kan använda ID-taggar på alla fält om du vill det, eller vad är målet med en sida utan markdown ?

2021-06-30 10:19 UTC, GETEXSM commented
commita in Kamstrup som tillverkare då iaf, för det saknas elmätare.
Sen som jag skrev, S211 är Sagemcom´s benämning på en specifik mätare, inte deras utbud av nya smarta mätare.

2021-06-30 10:33 UTC, Krolken commented
> SEO ? Det är bara något man bryr sig om man ska pusha reklam eller vinstintresse, detta är en tekniksida likt Wikipedia som ska vara lätt att läsa för människor.
> Om du skulle få alla elbolag i den listan så skulle den bli enormt lång sida, samt 80% dött utrymme till höger om texten.
> Istället med Tabell så formateras allt så den tar upp mer av sidans bredd och man forcerar in informationen likt andra har skrivet den, annars kommer det garanterat bli så rörigt att snabbt leta upp exakt vad man letar efter då folk kommer skriva på olika sätt, som du redan gjort.
> Sen vad menar du med Markdown ? ska du bygga hel hemsida utan HTML ? du kan använda ID-taggar på alla fält om du vill det, eller vad är målet med en sida utan markdown ?

Där finns knappt någon HTML alls i repot just nu. Allt är i markdown.
Här kan du se till exempel hur man göra en tabell: https://raw.githubusercontent.com/u9n/hanporten/main/docs/svenska/porten.md

SEO är viktigt för att folk ska hitta till sidan och få bra ranking i sökmotorer.

Just nu är inte alla elbolag med och jag tycker att det blir klöddigt med en tabell. Möjligtvis så kan man titta på det senare när det nuvarande formatet blir jobbigt att hantera. Men det är skönt att kunna skicka en länk med info som: https://hanporten.se/natbolag.html#eon.

2022-03-10 19:36 UTC, dannil76 requested changes
Agree with @Krolken. Try to keep it consistent with how the page is structured. Use markdown syntax. :)

2022-05-20 21:16 UTC, closed without merging